name: build to page

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "page"
  cancel-in-progress: true

jobs:
  prod:
    if: contains(github.event.head_commit.message, '[prod]') || contains(github.event.head_commit.message, '[all]')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies & build

        run: |
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: tribyte.io
